image: node:latest

stages:
  - build
  - verify
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

prettier:
  stage: verify
  script:
    - npm run prettier
  dependencies:
    - build

lint:
  stage: verify
  script:
    - npm run lint
  dependencies:
    - build

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r src/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
