image: node:latest

stages:
  - verify
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

verify:
  stage: verify
  script:
    - npm install
    - npm run lint
    - npm run prettier -- --check

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r src/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
