name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm ci

  format:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "latest"
      - name: Format
        run: npm run format

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "latest"
      - name: Lint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [format, lint]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        run: |
          mkdir public
          cp -r src/* public/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
